

import { AgeRange, HealthPlan } from './types';

export const AGE_RANGES = Object.values(AgeRange);

// Helper for Categories
const CAT_PF = 'PF';
const CAT_PME_1 = 'PME_1';
const CAT_PME_2 = 'PME_2';
const CAT_PME_30 = 'PME_30';

// --- HELPER DATA FOR DETAILS ---

const GRACE_PERIOD_STANDARD = [
  "24 horas: Urgência e Emergência",
  "30 dias: Consultas e Exames Simples",
  "180 dias: Exames Complexos, Internações e Cirurgias",
  "10 meses: Parto",
  "24 meses: Doenças Preexistentes"
];

// DATA STRUCTURE FOR AMHEMED GRACE PERIODS
export const AMHEMED_GRACE_DATA = {
  normal: [
    { label: "Urgência e Emergência", value: "24 HORAS" },
    { label: "Consultas Núcleo de Especialidades (Clínica Amhemed)", value: "24 HORAS" },
    { label: "Consultas Rede Credenciada", value: "30 DIAS" },
    { label: "Exames Complementares Básicos, Laboratoriais Básicos", value: "24 HORAS" },
    { label: "Exames Complexos, Internação Clínica/Cirúrgica/Psiquiátrica", value: "180 DIAS" },
    { label: "Terapias Simples (Psicologia, Fonoaudiologia)", value: "180 DIAS" },
    { label: "Terapias Específicas (ABA, BOBATH, etc)", value: "180 DIAS" },
    { label: "Partos e Termos", value: "300 DIAS" },
    { label: "Doenças e Lesões Pré Existentes", value: "24 MESES" }
  ],
  red1: [
    { label: "Urgência e Emergência", value: "24 HORAS" },
    { label: "Consultas Núcleo de Especialidades (Clínica Amhemed)", value: "24 HORAS" },
    { label: "Consultas Rede Credenciada", value: "30 DIAS" },
    { label: "Exames Complementares Básicos, Laboratoriais Básicos", value: "24 HORAS" },
    { label: "Exames Complexos, Internação Clínica/Cirúrgica/Psiquiátrica", value: "90 DIAS", highlight: true },
    { label: "Terapias Simples (Psicologia, Fonoaudiologia)", value: "180 DIAS" },
    { label: "Terapias Específicas (ABA, BOBATH, etc)", value: "180 DIAS" },
    { label: "Partos e Termos", value: "300 DIAS" },
    { label: "Doenças e Lesões Pré Existentes", value: "24 MESES" }
  ],
  red2: [
    { label: "Urgência e Emergência", value: "24 HORAS" },
    { label: "Consultas Núcleo de Especialidades (Clínica Amhemed)", value: "24 HORAS" },
    { label: "Consultas Rede Credenciada", value: "30 DIAS" },
    { label: "Exames Complementares Básicos, Laboratoriais Básicos", value: "24 HORAS" },
    { label: "Exames Complexos, Internação Clínica/Cirúrgica/Psiquiátrica", value: "60 DIAS", highlight: true },
    { label: "Terapias Simples (Psicologia, Fonoaudiologia)", value: "180 DIAS" },
    { label: "Terapias Específicas (ABA, BOBATH, etc)", value: "180 DIAS" },
    { label: "Partos e Termos", value: "300 DIAS" },
    { label: "Doenças e Lesões Pré Existentes", value: "24 MESES" }
  ]
};

// DATA STRUCTURE FOR FENIX MEDICAL GRACE PERIODS
export const FENIX_GRACE_DATA = {
  standard: [
    { label: "Urgência e Emergência", value: "24 HORAS" },
    { label: "Consultas e Exames Simples", value: "30 DIAS" },
    { label: "Exames Especiais e Terapias", value: "180 DIAS" },
    { label: "Internações e Cirurgias", value: "180 DIAS" },
    { label: "Parto", value: "300 DIAS" },
    { label: "Doenças Preexistentes", value: "24 MESES" }
  ],
  reduced: [
    { label: "Urgência e Emergência", value: "24 HORAS" },
    { label: "Consultas e Exames Simples", value: "24 HORAS", highlight: true },
    { label: "Exames Especiais e Terapias", value: "30 DIAS", highlight: true },
    { label: "Internações e Cirurgias", value: "120 DIAS", highlight: true },
    { label: "Parto", value: "300 DIAS" },
    { label: "Doenças Preexistentes", value: "24 MESES" }
  ]
};

const GRACE_PERIOD_PME_30 = [
  "Isenção total de carências (exceto parto e preexistentes para algumas operadoras).",
  "Consulte condições específicas para o seu CNPJ."
];

const COPAY_NONE = [
  { service: "Consultas", value: "R$ 0,00" },
  { service: "Exames Simples", value: "R$ 0,00" },
  { service: "Exames Complexos", value: "R$ 0,00" },
  { service: "Pronto Socorro", value: "R$ 0,00" },
  { service: "Internação", value: "R$ 0,00" },
  { service: "Terapias Simples", value: "R$ 0,00" },
  { service: "Terapias Especiais", value: "R$ 0,00" }
];

const COPAY_PARTIAL_AMHEMED = [
  { service: "Consultas Eletivas", value: "R$ 0,00 (Isento)" },
  { service: "Exames Simples", value: "R$ 0,00 (Isento)" },
  { service: "Pronto Socorro", value: "R$ 35,00" },
  { service: "Internação", value: "R$ 250,00 (Evento)" },
  { service: "Terapias Simples", value: "R$ 25,00" },
  { service: "Terapias Especiais", value: "R$ 25,00" }
];

const COPAY_FULL_AMHEMED = [
  { service: "Consultas", value: "R$ 25,00" },
  { service: "Exames Simples", value: "R$ 10,00" },
  { service: "Exames Complexos", value: "R$ 45,00" },
  { service: "Pronto Socorro", value: "R$ 45,00" },
  { service: "Internação", value: "R$ 250,00 (Evento)" },
  { service: "Terapias Simples", value: "R$ 25,00" },
  { service: "Terapias Especiais", value: "R$ 25,00" }
];

// Specific Copay for Amhe Ideal PME
const COPAY_PARTIAL_AMHE_IDEAL_PME = [
  { service: "Consultas", value: "sem coparticipação" },
  { service: "Pronto Socorro", value: "sem coparticipação" },
  { service: "Exames", value: "sem coparticipação" },
  { service: "Internações", value: "sem coparticipação" },
  { service: "Terapias Simples", value: "até R$ 40,00 por sessão" },
  { service: "Terapias Especiais", value: "até R$ 100,00 por sessão" }
];

const COPAY_FULL_AMHE_IDEAL_PME = [
  { service: "Consultas", value: "R$ 49,90" },
  { service: "Pronto Socorro", value: "R$ 54,90" },
  { service: "Exames", value: "de R$ 2,00 a R$ 100,00" },
  { service: "Internações", value: "R$ 250,00 por internação" },
  { service: "Terapias Simples", value: "até R$ 40,00 por sessão" },
  { service: "Terapias Especiais", value: "até R$ 100,00 por sessão" }
];

// Specific Copay for Amhe+ PME (1 and 2-29 lives)
const COPAY_PARTIAL_AMHE_PLUS_PME = [
  { service: "Consultas", value: "sem coparticipação" },
  { service: "Pronto Socorro", value: "sem coparticipação" },
  { service: "Exames", value: "sem coparticipação" },
  { service: "Internações", value: "sem coparticipação" },
  { service: "Terapias Simples", value: "até R$ 40,00 por sessão" },
  { service: "Terapias Especiais", value: "até R$ 100,00 por sessão" }
];

const COPAY_FULL_AMHE_PLUS_PME = [
  { service: "Consultas", value: "R$ 30,00" },
  { service: "Pronto Socorro", value: "R$ 35,00" },
  { service: "Exames", value: "de R$ 2,00 a R$ 100,00" },
  { service: "Internações", value: "R$ 200,00 por internação" },
  { service: "Terapias Simples", value: "até R$ 40,00 por sessão" },
  { service: "Terapias Especiais", value: "até R$ 100,00 por sessão" }
];


const COPAY_PARTIAL_GNDI = [
  { service: "Consultas", value: "Isento" },
  { service: "Pronto Socorro", value: "Isento" },
  { service: "Exames Simples", value: "Isento" },
  { service: "Exames Especiais", value: "Isento" },
  { service: "Internação", value: "Isento" },
  { service: "Terapias Simples", value: "R$ 40,84" },
  { service: "Terapias Especiais", value: "R$ 75,84" }
];

const COPAY_FULL_GNDI = [
  { service: "Consultas", value: "R$ 41,95" },
  { service: "Pronto Socorro", value: "R$ 59,44" },
  { service: "Exames Simples", value: "até R$ 49,54" },
  { service: "Exames Especiais", value: "até R$ 121,09" },
  { service: "Internação", value: "R$ 250,00" },
  { service: "Terapias Simples", value: "R$ 40,84" },
  { service: "Terapias Especiais", value: "R$ 75,84" }
];

const COPAY_PARTIAL_GNDI_SMART200 = [
  { service: "Consultas", value: "Isento" },
  { service: "Pronto Socorro", value: "Isento" },
  { service: "Exames Simples", value: "Isento" },
  { service: "Exames Especiais", value: "Isento" },
  { service: "Internação", value: "Isento" },
  { service: "Terapias Simples", value: "até R$ 40,00" },
  { service: "Terapias Especiais", value: "até R$ 40,00" }
];

const COPAY_FULL_GNDI_SMART200 = [
  { service: "Consultas", value: "R$ 30,00" },
  { service: "Pronto Socorro", value: "R$ 80,00" },
  { service: "Exames Simples", value: "até R$ 20,00" },
  { service: "Exames Especiais", value: "até R$ 100,00" },
  { service: "Internação", value: "R$ 250,00" },
  { service: "Terapias Simples", value: "até R$ 40,00" },
  { service: "Terapias Especiais", value: "até R$ 40,00" }
];

const COPAY_FULL_UNIMED = [
  { service: "Consultas", value: "R$ 35,00" },
  { service: "Pronto Socorro", value: "R$ 50,00" },
  { service: "Exames Simples", value: "R$ 5,90" },
  { service: "Exames Especiais", value: "até R$ 49,90" },
  { service: "Internação", value: "Isento" },
  { service: "Terapias Simples", value: "R$ 9,90" },
  { service: "Terapias Especiais", value: "R$ 49,90" }
];

const COPAY_PARTIAL_AMIL = [
  { service: "Consultas", value: "Isento" },
  { service: "Pronto Socorro", value: "Isento" },
  { service: "Exames Simples", value: "Isento" },
  { service: "Exames Especiais", value: "Isento" },
  { service: "Internação", value: "Isento" },
  { service: "Terapias Simples", value: "até R$ 50,00" },
  { service: "Terapias Especiais", value: "até R$ 50,00" }
];

const COPAY_FULL_AMIL = [
  { service: "Consultas", value: "até R$ 30,00" },
  { service: "Pronto Socorro", value: "até R$ 90,00" },
  { service: "Exames Simples", value: "até R$ 25,00" },
  { service: "Exames Especiais", value: "até R$ 110,00" },
  { service: "Internação", value: "R$ 220,00" },
  { service: "Terapias Simples", value: "até R$ 50,00" },
  { service: "Terapias Especiais", value: "até R$ 50,00" }
];

const COPAY_FULL_FENIX = [
  { service: "Consultas", value: "R$ 25,00" },
  { service: "Pronto Socorro", value: "R$ 35,00" },
  { service: "Exames Simples", value: "Isento" },
  { service: "Exames Especiais", value: "Isento" },
  { service: "Internação", value: "Isento" },
  { service: "Terapias Simples", value: "Isento" },
  { service: "Terapias Especiais", value: "R$ 35,00" }
];

const COPAY_FULL_EVA = [
  { service: "Consultas", value: "até R$ 40,00" },
  { service: "Pronto Socorro", value: "até R$ 70,00" },
  { service: "Exames Simples", value: "até R$ 50,00" },
  { service: "Exames Especiais", value: "até R$ 150,00" },
  { service: "Internação", value: "R$ 250,00" },
  { service: "Terapias Simples", value: "até R$ 40,00" },
  { service: "Terapias Especiais", value: "até R$ 150,00" }
];

// Helper function to generate prices based on a base value
const generatePrices = (base: number): { [key: string]: number } => ({
  [AgeRange.RANGE_0_18]: base,
  [AgeRange.RANGE_19_23]: Math.round(base * 1.25),
  [AgeRange.RANGE_24_28]: Math.round(base * 1.5),
  [AgeRange.RANGE_29_33]: Math.round(base * 1.75),
  [AgeRange.RANGE_34_38]: Math.round(base * 2.0),
  [AgeRange.RANGE_39_43]: Math.round(base * 2.4),
  [AgeRange.RANGE_44_48]: Math.round(base * 3.0),
  [AgeRange.RANGE_49_53]: Math.round(base * 3.7),
  [AgeRange.RANGE_54_58]: Math.round(base * 4.5),
  [AgeRange.RANGE_59_PLUS]: Math.round(base * 6.0),
});

export const MOCK_PLANS: HealthPlan[] = [
  // ==========================================================================
  // AMHEMED
  // Colors: Ideal (Blue-900), Amhe+ (Teal-600), Plus (Slate-900)
  // ==========================================================================

  // --- Amhe Ideal (PME 2+ Only) ---
  {
    id: 'amhe-ideal-part',
    name: 'Amhe Ideal',
    operator: 'Amhemed',
    type: 'Enfermaria',
    coparticipationType: 'partial',
    logoColor: 'bg-blue-900',
    description: 'Ideal para empresas.',
    hospitals: ['Hospital Amhemed', 'BOS', 'Santa Lucinda'],
    categories: [CAT_PME_2, CAT_PME_30],
    coverage: 'Sorocaba',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_PARTIAL_AMHE_IDEAL_PME,
    prices: {
      [AgeRange.RANGE_0_18]: 159.51,
      [AgeRange.RANGE_19_23]: 187.90,
      [AgeRange.RANGE_24_28]: 221.05,
      [AgeRange.RANGE_29_33]: 221.05,
      [AgeRange.RANGE_34_38]: 221.05,
      [AgeRange.RANGE_39_43]: 262.90,
      [AgeRange.RANGE_44_48]: 339.00,
      [AgeRange.RANGE_49_53]: 442.00,
      [AgeRange.RANGE_54_58]: 579.00,
      [AgeRange.RANGE_59_PLUS]: 835.12,
    },
  },
  {
    id: 'amhe-ideal-full',
    name: 'Amhe Ideal',
    operator: 'Amhemed',
    type: 'Enfermaria',
    coparticipationType: 'full',
    logoColor: 'bg-blue-900',
    description: 'Opção econômica.',
    hospitals: ['Hospital Amhemed', 'BOS', 'Santa Lucinda'],
    categories: [CAT_PME_2, CAT_PME_30],
    coverage: 'Sorocaba',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_AMHE_IDEAL_PME,
    prices: {
      [AgeRange.RANGE_0_18]: 101.86,
      [AgeRange.RANGE_19_23]: 137.01,
      [AgeRange.RANGE_24_28]: 161.29,
      [AgeRange.RANGE_29_33]: 161.29,
      [AgeRange.RANGE_34_38]: 161.29,
      [AgeRange.RANGE_39_43]: 192.73,
      [AgeRange.RANGE_44_48]: 248.39,
      [AgeRange.RANGE_49_53]: 311.08,
      [AgeRange.RANGE_54_58]: 422.58,
      [AgeRange.RANGE_59_PLUS]: 593.76,
    },
  },

  // --- Amhe+ (PME 1 Only) ---
  {
    id: 'amhe-mais-part-pme1',
    name: 'Amhe+',
    operator: 'Amhemed',
    type: 'Enfermaria',
    coparticipationType: 'partial',
    logoColor: 'bg-teal-600',
    description: 'Rede credenciada regional.',
    hospitals: ['Hospital Amhemed', 'BOS', 'Santa Lucinda'],
    categories: [CAT_PME_1],
    coverage: 'Sorocaba',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_PARTIAL_AMHE_PLUS_PME,
    prices: {
      [AgeRange.RANGE_0_18]: 187.46,
      [AgeRange.RANGE_19_23]: 253.04,
      [AgeRange.RANGE_24_28]: 299.04,
      [AgeRange.RANGE_29_33]: 299.04,
      [AgeRange.RANGE_34_38]: 299.04,
      [AgeRange.RANGE_39_43]: 355.18,
      [AgeRange.RANGE_44_48]: 461.73,
      [AgeRange.RANGE_49_53]: 600.26,
      [AgeRange.RANGE_54_58]: 732.44,
      [AgeRange.RANGE_59_PLUS]: 1056.12,
    },
  },
  {
    id: 'amhe-mais-full-pme1',
    name: 'Amhe+',
    operator: 'Amhemed',
    type: 'Enfermaria',
    coparticipationType: 'full',
    logoColor: 'bg-teal-600',
    description: 'Rede credenciada regional.',
    hospitals: ['Hospital Amhemed', 'BOS', 'Santa Lucinda'],
    categories: [CAT_PME_1],
    coverage: 'Sorocaba',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_AMHE_PLUS_PME,
    prices: {
      [AgeRange.RANGE_0_18]: 142.80,
      [AgeRange.RANGE_19_23]: 192.75,
      [AgeRange.RANGE_24_28]: 227.79,
      [AgeRange.RANGE_29_33]: 227.79,
      [AgeRange.RANGE_34_38]: 227.79,
      [AgeRange.RANGE_39_43]: 270.55,
      [AgeRange.RANGE_44_48]: 351.72,
      [AgeRange.RANGE_49_53]: 457.24,
      [AgeRange.RANGE_54_58]: 594.41,
      [AgeRange.RANGE_59_PLUS]: 856.72,
    },
  },

  // --- Amhe+ (PF Only) ---
  {
    id: 'amhe-mais-part-pf',
    name: 'Amhe+',
    operator: 'Amhemed',
    type: 'Enfermaria',
    coparticipationType: 'partial',
    logoColor: 'bg-teal-600',
    description: 'Rede credenciada regional.',
    hospitals: ['Hospital Amhemed', 'BOS', 'Santa Lucinda'],
    categories: [CAT_PF],
    coverage: 'Sorocaba',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_PARTIAL_AMHEMED,
    prices: {
      [AgeRange.RANGE_0_18]: 299.90,
      [AgeRange.RANGE_19_23]: 300.98,
      [AgeRange.RANGE_24_28]: 323.92,
      [AgeRange.RANGE_29_33]: 327.31,
      [AgeRange.RANGE_34_38]: 339.64,
      [AgeRange.RANGE_39_43]: 426.67,
      [AgeRange.RANGE_44_48]: 552.45,
      [AgeRange.RANGE_49_53]: 652.72,
      [AgeRange.RANGE_54_58]: 771.09,
      [AgeRange.RANGE_59_PLUS]: 1145.17,
    },
  },
  {
    id: 'amhe-mais-full-pf',
    name: 'Amhe+',
    operator: 'Amhemed',
    type: 'Enfermaria',
    coparticipationType: 'full',
    logoColor: 'bg-teal-600',
    description: 'Rede credenciada regional.',
    hospitals: ['Hospital Amhemed', 'BOS', 'Santa Lucinda'],
    categories: [CAT_PF],
    coverage: 'Sorocaba',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_AMHEMED,
    prices: {
      [AgeRange.RANGE_0_18]: 199.99,
      [AgeRange.RANGE_19_23]: 245.52,
      [AgeRange.RANGE_24_28]: 263.89,
      [AgeRange.RANGE_29_33]: 285.74,
      [AgeRange.RANGE_34_38]: 309.93,
      [AgeRange.RANGE_39_43]: 330.22,
      [AgeRange.RANGE_44_48]: 446.33,
      [AgeRange.RANGE_49_53]: 493.90,
      [AgeRange.RANGE_54_58]: 637.23,
      [AgeRange.RANGE_59_PLUS]: 978.84,
    },
  },

  // --- Amhe+ (PME 2-29) ---
  {
    id: 'amhe-mais-part-pme',
    name: 'Amhe+',
    operator: 'Amhemed',
    type: 'Enfermaria',
    coparticipationType: 'partial',
    logoColor: 'bg-teal-600',
    description: 'Rede credenciada regional.',
    hospitals: ['Hospital Amhemed', 'BOS', 'Santa Lucinda'],
    categories: [CAT_PME_2, CAT_PME_30],
    coverage: 'Sorocaba',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_PARTIAL_AMHE_PLUS_PME,
    prices: {
      [AgeRange.RANGE_0_18]: 183.44,
      [AgeRange.RANGE_19_23]: 216.09,
      [AgeRange.RANGE_24_28]: 254.21,
      [AgeRange.RANGE_29_33]: 254.21,
      [AgeRange.RANGE_34_38]: 254.21,
      [AgeRange.RANGE_39_43]: 302.34,
      [AgeRange.RANGE_44_48]: 389.85,
      [AgeRange.RANGE_49_53]: 508.30,
      [AgeRange.RANGE_54_58]: 665.85,
      [AgeRange.RANGE_59_PLUS]: 960.39,
    },
  },
  {
    id: 'amhe-mais-full-pme',
    name: 'Amhe+',
    operator: 'Amhemed',
    type: 'Enfermaria',
    coparticipationType: 'full',
    logoColor: 'bg-teal-600',
    description: 'Rede credenciada regional.',
    hospitals: ['Hospital Amhemed', 'BOS', 'Santa Lucinda'],
    categories: [CAT_PME_2, CAT_PME_30],
    coverage: 'Sorocaba',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_AMHE_PLUS_PME,
    prices: {
      [AgeRange.RANGE_0_18]: 125.04,
      [AgeRange.RANGE_19_23]: 168.20,
      [AgeRange.RANGE_24_28]: 198.00,
      [AgeRange.RANGE_29_33]: 198.00,
      [AgeRange.RANGE_34_38]: 198.00,
      [AgeRange.RANGE_39_43]: 236.59,
      [AgeRange.RANGE_44_48]: 304.92,
      [AgeRange.RANGE_49_53]: 381.88,
      [AgeRange.RANGE_54_58]: 518.76,
      [AgeRange.RANGE_59_PLUS]: 728.90,
    },
  },

  // --- Amhe Plus (PF) ---
  {
    id: 'amhe-plus-part-pf',
    name: 'Amhe Plus',
    operator: 'Amhemed',
    type: 'Apartamento',
    coparticipationType: 'partial',
    logoColor: 'bg-slate-900',
    description: 'Acomodação individual.',
    hospitals: ['Hospital Amhemed', 'BOS', 'Santa Lucinda'],
    categories: [CAT_PF],
    coverage: 'Sorocaba, Araçoiaba da Serra; Boituva; Capela do Alto; Iperó; Itapetininga; Pilar do Sul; Porto Feliz; Salto; Salto de Pirapora; São Roque; Votorantim.',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_PARTIAL_AMHEMED,
    prices: {
      [AgeRange.RANGE_0_18]: 319.20,
      [AgeRange.RANGE_19_23]: 373.21,
      [AgeRange.RANGE_24_28]: 437.11,
      [AgeRange.RANGE_29_33]: 452.12,
      [AgeRange.RANGE_34_38]: 506.78,
      [AgeRange.RANGE_39_43]: 598.00,
      [AgeRange.RANGE_44_48]: 705.66,
      [AgeRange.RANGE_49_53]: 835.21,
      [AgeRange.RANGE_54_58]: 1154.52,
      [AgeRange.RANGE_59_PLUS]: 1544.93,
    },
  },
  {
    id: 'amhe-plus-full-pf',
    name: 'Amhe Plus',
    operator: 'Amhemed',
    type: 'Apartamento',
    coparticipationType: 'full',
    logoColor: 'bg-slate-900',
    description: 'Acomodação individual.',
    hospitals: ['Hospital Amhemed', 'BOS', 'Santa Lucinda'],
    categories: [CAT_PF],
    coverage: 'Sorocaba, Araçoiaba da Serra; Boituva; Capela do Alto; Iperó; Itapetininga; Pilar do Sul; Porto Feliz; Salto; Salto de Pirapora; São Roque; Votorantim.',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_AMHEMED,
    prices: {
      [AgeRange.RANGE_0_18]: 225.75,
      [AgeRange.RANGE_19_23]: 280.10,
      [AgeRange.RANGE_24_28]: 312.28,
      [AgeRange.RANGE_29_33]: 330.75,
      [AgeRange.RANGE_34_38]: 366.45,
      [AgeRange.RANGE_39_43]: 418.95,
      [AgeRange.RANGE_44_48]: 529.78,
      [AgeRange.RANGE_49_53]: 722.40,
      [AgeRange.RANGE_54_58]: 943.95,
      [AgeRange.RANGE_59_PLUS]: 1174.41,
    },
  },

  // --- Amhe Plus (PME 2-29) ---
  {
    id: 'amhe-plus-part-pme',
    name: 'Amhe Plus',
    operator: 'Amhemed',
    type: 'Apartamento',
    coparticipationType: 'partial',
    logoColor: 'bg-slate-900',
    description: 'Acomodação individual.',
    hospitals: ['Hospital Amhemed', 'BOS', 'Santa Lucinda'],
    categories: [CAT_PME_2, CAT_PME_30],
    coverage: 'Sorocaba, Araçoiaba da Serra; Boituva; Capela do Alto; Iperó; Itapetininga; Pilar do Sul; Porto Feliz; Salto; Salto de Pirapora; São Roque; Votorantim.',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_PARTIAL_AMHE_PLUS_PME,
    prices: {
      [AgeRange.RANGE_0_18]: 199.00,
      [AgeRange.RANGE_19_23]: 271.00,
      [AgeRange.RANGE_24_28]: 320.38,
      [AgeRange.RANGE_29_33]: 379.00,
      [AgeRange.RANGE_34_38]: 347.00,
      [AgeRange.RANGE_39_43]: 381.91,
      [AgeRange.RANGE_44_48]: 492.97,
      [AgeRange.RANGE_49_53]: 647.00,
      [AgeRange.RANGE_54_58]: 841.00,
      [AgeRange.RANGE_59_PLUS]: 1192.48,
    },
  },
  {
    id: 'amhe-plus-full-pme',
    name: 'Amhe Plus',
    operator: 'Amhemed',
    type: 'Apartamento',
    coparticipationType: 'full',
    logoColor: 'bg-slate-900',
    description: 'Acomodação individual.',
    hospitals: ['Hospital Amhemed', 'BOS', 'Santa Lucinda'],
    categories: [CAT_PME_2, CAT_PME_30],
    coverage: 'Sorocaba, Araçoiaba da Serra; Boituva; Capela do Alto; Iperó; Itapetininga; Pilar do Sul; Porto Feliz; Salto; Salto de Pirapora; São Roque; Votorantim.',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_AMHE_PLUS_PME,
    prices: {
      [AgeRange.RANGE_0_18]: 145.90,
      [AgeRange.RANGE_19_23]: 189.90,
      [AgeRange.RANGE_24_28]: 234.90,
      [AgeRange.RANGE_29_33]: 245.00,
      [AgeRange.RANGE_34_38]: 248.15,
      [AgeRange.RANGE_39_43]: 278.00,
      [AgeRange.RANGE_44_48]: 359.00,
      [AgeRange.RANGE_49_53]: 469.00,
      [AgeRange.RANGE_54_58]: 610.00,
      [AgeRange.RANGE_59_PLUS]: 879.00,
    },
  },

  // ==========================================================================
  // GNDI (NOTREDAME)
  // Color: Orange-500
  // ==========================================================================

  // --- Nosso Plano (PME 1 Only) ---
  {
    id: 'gndi-nosso-part-pme1',
    name: 'Nosso Plano',
    operator: 'GNDI NotreDame',
    type: 'Enfermaria',
    coparticipationType: 'partial',
    logoColor: 'bg-orange-500',
    description: 'Rede própria GNDI.',
    hospitals: ['Hospital NotreCare', 'Modelo'],
    categories: [CAT_PME_1],
    coverage: 'Sorocaba',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_PARTIAL_GNDI,
    prices: {
      [AgeRange.RANGE_0_18]: 194.26,
      [AgeRange.RANGE_19_23]: 262.22,
      [AgeRange.RANGE_24_28]: 309.89,
      [AgeRange.RANGE_29_33]: 309.89,
      [AgeRange.RANGE_34_38]: 309.89,
      [AgeRange.RANGE_39_43]: 368.06,
      [AgeRange.RANGE_44_48]: 478.48,
      [AgeRange.RANGE_49_53]: 622.03,
      [AgeRange.RANGE_54_58]: 808.64,
      [AgeRange.RANGE_59_PLUS]: 1165.49,
    },
  },
  {
    id: 'gndi-nosso-full-pme1',
    name: 'Nosso Plano',
    operator: 'GNDI NotreDame',
    type: 'Enfermaria',
    coparticipationType: 'full',
    logoColor: 'bg-orange-500',
    description: 'Rede própria GNDI.',
    hospitals: ['Hospital NotreCare', 'Modelo'],
    categories: [CAT_PME_1],
    coverage: 'Sorocaba',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_GNDI,
    prices: {
      [AgeRange.RANGE_0_18]: 145.71,
      [AgeRange.RANGE_19_23]: 196.68,
      [AgeRange.RANGE_24_28]: 232.44,
      [AgeRange.RANGE_29_33]: 232.44,
      [AgeRange.RANGE_34_38]: 232.44,
      [AgeRange.RANGE_39_43]: 276.07,
      [AgeRange.RANGE_44_48]: 358.90,
      [AgeRange.RANGE_49_53]: 466.57,
      [AgeRange.RANGE_54_58]: 606.54,
      [AgeRange.RANGE_59_PLUS]: 874.20,
    },
  },

  // --- Nosso Plano (PF Only - Specific Prices) ---
  {
    id: 'gndi-nosso-part-pf',
    name: 'Nosso Plano',
    operator: 'GNDI NotreDame',
    type: 'Enfermaria',
    coparticipationType: 'partial',
    logoColor: 'bg-orange-500',
    description: 'Rede própria GNDI.',
    hospitals: ['Hospital NotreCare', 'Modelo'],
    categories: [CAT_PF],
    coverage: 'Sorocaba',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_PARTIAL_GNDI,
    prices: {
      [AgeRange.RANGE_0_18]: 261.60,
      [AgeRange.RANGE_19_23]: 318.92,
      [AgeRange.RANGE_24_28]: 327.76,
      [AgeRange.RANGE_29_33]: 364.17,
      [AgeRange.RANGE_34_38]: 376.34,
      [AgeRange.RANGE_39_43]: 413.98,
      [AgeRange.RANGE_44_48]: 589.39,
      [AgeRange.RANGE_49_53]: 598.17,
      [AgeRange.RANGE_54_58]: 758.30,
      [AgeRange.RANGE_59_PLUS]: 1167.78,
    },
  },
  {
    id: 'gndi-nosso-full-pf',
    name: 'Nosso Plano',
    operator: 'GNDI NotreDame',
    type: 'Enfermaria',
    coparticipationType: 'full',
    logoColor: 'bg-orange-500',
    description: 'Rede própria GNDI.',
    hospitals: ['Hospital NotreCare', 'Modelo'],
    categories: [CAT_PF],
    coverage: 'Sorocaba',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_GNDI,
    prices: {
      [AgeRange.RANGE_0_18]: 207.03,
      [AgeRange.RANGE_19_23]: 252.38,
      [AgeRange.RANGE_24_28]: 259.37,
      [AgeRange.RANGE_29_33]: 288.19,
      [AgeRange.RANGE_34_38]: 297.82,
      [AgeRange.RANGE_39_43]: 327.59,
      [AgeRange.RANGE_44_48]: 466.39,
      [AgeRange.RANGE_49_53]: 473.35,
      [AgeRange.RANGE_54_58]: 600.07,
      [AgeRange.RANGE_59_PLUS]: 924.11,
    },
  },

  // --- Nosso Plano (PME 2-29) ---
  {
    id: 'gndi-nosso-part-pme',
    name: 'Nosso Plano',
    operator: 'GNDI NotreDame',
    type: 'Enfermaria',
    coparticipationType: 'partial',
    logoColor: 'bg-orange-500',
    description: 'Rede própria GNDI.',
    hospitals: ['Hospital NotreCare', 'Modelo'],
    categories: [CAT_PME_2, CAT_PME_30],
    coverage: 'Sorocaba',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_PARTIAL_GNDI,
    prices: {
      [AgeRange.RANGE_0_18]: 139.97,
      [AgeRange.RANGE_19_23]: 188.93,
      [AgeRange.RANGE_24_28]: 223.28,
      [AgeRange.RANGE_29_33]: 223.28,
      [AgeRange.RANGE_34_38]: 223.28,
      [AgeRange.RANGE_39_43]: 265.19,
      [AgeRange.RANGE_44_48]: 344.74,
      [AgeRange.RANGE_49_53]: 448.17,
      [AgeRange.RANGE_54_58]: 582.63,
      [AgeRange.RANGE_59_PLUS]: 839.74,
    },
  },
  {
    id: 'gndi-nosso-full-pme',
    name: 'Nosso Plano',
    operator: 'GNDI NotreDame',
    type: 'Enfermaria',
    coparticipationType: 'full',
    logoColor: 'bg-orange-500',
    description: 'Rede própria GNDI.',
    hospitals: ['Hospital NotreCare', 'Modelo'],
    categories: [CAT_PME_2, CAT_PME_30],
    coverage: 'Sorocaba',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_GNDI,
    prices: {
      [AgeRange.RANGE_0_18]: 104.99,
      [AgeRange.RANGE_19_23]: 141.71,
      [AgeRange.RANGE_24_28]: 167.48,
      [AgeRange.RANGE_29_33]: 167.48,
      [AgeRange.RANGE_34_38]: 167.48,
      [AgeRange.RANGE_39_43]: 198.92,
      [AgeRange.RANGE_44_48]: 258.60,
      [AgeRange.RANGE_49_53]: 336.18,
      [AgeRange.RANGE_54_58]: 437.03,
      [AgeRange.RANGE_59_PLUS]: 629.90,
    },
  },

  // --- NotreLife (PF Only) ---
  {
    id: 'gndi-life-part-pf',
    name: 'NotreLife',
    operator: 'GNDI NotreDame',
    type: 'Enfermaria',
    coparticipationType: 'partial',
    logoColor: 'bg-amber-600',
    description: 'Plano individual.',
    hospitals: ['Hospital NotreCare', 'Modelo'],
    categories: [CAT_PF],
    coverage: 'Regional (Sorocaba e Jundiaí)',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_PARTIAL_GNDI,
    prices: {
      [AgeRange.RANGE_0_18]: 331.21,
      [AgeRange.RANGE_19_23]: 363.40,
      [AgeRange.RANGE_24_28]: 373.47,
      [AgeRange.RANGE_29_33]: 414.96,
      [AgeRange.RANGE_34_38]: 428.82,
      [AgeRange.RANGE_39_43]: 471.72,
      [AgeRange.RANGE_44_48]: 671.60,
      [AgeRange.RANGE_49_53]: 681.58,
      [AgeRange.RANGE_54_58]: 864.03,
      [AgeRange.RANGE_59_PLUS]: 1330.63,
    },
  },
  {
    id: 'gndi-life-full-pf',
    name: 'NotreLife',
    operator: 'GNDI NotreDame',
    type: 'Enfermaria',
    coparticipationType: 'full',
    logoColor: 'bg-amber-600',
    description: 'Plano individual.',
    hospitals: ['Hospital NotreCare', 'Modelo'],
    categories: [CAT_PF],
    coverage: 'Regional (Sorocaba e Jundiaí)',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_GNDI,
    prices: {
      [AgeRange.RANGE_0_18]: 262.12,
      [AgeRange.RANGE_19_23]: 287.60,
      [AgeRange.RANGE_24_28]: 295.58,
      [AgeRange.RANGE_29_33]: 328.41,
      [AgeRange.RANGE_34_38]: 339.38,
      [AgeRange.RANGE_39_43]: 373.34,
      [AgeRange.RANGE_44_48]: 531.53,
      [AgeRange.RANGE_49_53]: 539.43,
      [AgeRange.RANGE_54_58]: 683.82,
      [AgeRange.RANGE_59_PLUS]: 1053.10,
    },
  },

  // --- Smart 200up (PME 1) ---
  {
    id: 'gndi-200-part-pme1',
    name: 'Smart 200up',
    operator: 'GNDI NotreDame',
    type: 'Enfermaria',
    coparticipationType: 'partial',
    logoColor: 'bg-amber-500',
    description: 'Rede ampla.',
    hospitals: ['Hospital NotreCare', 'Modelo'],
    categories: [CAT_PME_1],
    coverage: 'Sorocaba, Itu, Votorantim entre outras cidades de São Paulo',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_PARTIAL_GNDI_SMART200,
    prices: {
      [AgeRange.RANGE_0_18]: 246.14,
      [AgeRange.RANGE_19_23]: 332.24,
      [AgeRange.RANGE_24_28]: 392.64,
      [AgeRange.RANGE_29_33]: 392.64,
      [AgeRange.RANGE_34_38]: 392.64,
      [AgeRange.RANGE_39_43]: 466.33,
      [AgeRange.RANGE_44_48]: 606.23,
      [AgeRange.RANGE_49_53]: 788.09,
      [AgeRange.RANGE_54_58]: 1024.52,
      [AgeRange.RANGE_59_PLUS]: 1476.65,
    },
  },
  {
    id: 'gndi-200-full-pme1',
    name: 'Smart 200up',
    operator: 'GNDI NotreDame',
    type: 'Enfermaria',
    coparticipationType: 'full',
    logoColor: 'bg-amber-500',
    description: 'Smart 200up com coparticipação total.',
    hospitals: ['Hospital NotreCare', 'Modelo'],
    categories: [CAT_PME_1],
    coverage: 'Sorocaba, Itu, Votorantim entre outras cidades de São Paulo',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_GNDI_SMART200,
    prices: {
      [AgeRange.RANGE_0_18]: 184.59,
      [AgeRange.RANGE_19_23]: 249.16,
      [AgeRange.RANGE_24_28]: 294.46,
      [AgeRange.RANGE_29_33]: 294.46,
      [AgeRange.RANGE_34_38]: 294.46,
      [AgeRange.RANGE_39_43]: 349.73,
      [AgeRange.RANGE_44_48]: 454.65,
      [AgeRange.RANGE_49_53]: 591.05,
      [AgeRange.RANGE_54_58]: 768.37,
      [AgeRange.RANGE_59_PLUS]: 1107.45,
    },
  },

  // --- Smart 200up (PME 2-29) ---
  {
    id: 'gndi-200-part-pme',
    name: 'Smart 200up',
    operator: 'GNDI NotreDame',
    type: 'Enfermaria',
    coparticipationType: 'partial',
    logoColor: 'bg-amber-500',
    description: 'Rede ampla.',
    hospitals: ['Hospital NotreCare', 'Modelo'],
    categories: [CAT_PME_2, CAT_PME_30],
    coverage: 'Sorocaba, Itu, Votorantim entre outras cidades de São Paulo',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_PARTIAL_GNDI_SMART200,
    prices: {
      [AgeRange.RANGE_0_18]: 172.80,
      [AgeRange.RANGE_19_23]: 233.24,
      [AgeRange.RANGE_24_28]: 275.64,
      [AgeRange.RANGE_29_33]: 275.64,
      [AgeRange.RANGE_34_38]: 275.64,
      [AgeRange.RANGE_39_43]: 327.38,
      [AgeRange.RANGE_44_48]: 425.60,
      [AgeRange.RANGE_49_53]: 553.28,
      [AgeRange.RANGE_54_58]: 719.26,
      [AgeRange.RANGE_59_PLUS]: 1036.67,
    },
  },
  {
    id: 'gndi-200-full-pme',
    name: 'Smart 200up',
    operator: 'GNDI NotreDame',
    type: 'Enfermaria',
    coparticipationType: 'full',
    logoColor: 'bg-amber-500',
    description: 'Smart 200up com coparticipação total.',
    hospitals: ['Hospital NotreCare', 'Modelo'],
    categories: [CAT_PME_2, CAT_PME_30],
    coverage: 'Sorocaba, Itu, Votorantim entre outras cidades de São Paulo',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_GNDI_SMART200,
    prices: {
      [AgeRange.RANGE_0_18]: 129.59,
      [AgeRange.RANGE_19_23]: 174.92,
      [AgeRange.RANGE_24_28]: 206.76,
      [AgeRange.RANGE_29_33]: 206.76,
      [AgeRange.RANGE_34_38]: 206.76,
      [AgeRange.RANGE_39_43]: 245.53,
      [AgeRange.RANGE_44_48]: 319.19,
      [AgeRange.RANGE_49_53]: 414.94,
      [AgeRange.RANGE_54_58]: 539.43,
      [AgeRange.RANGE_59_PLUS]: 777.48,
    },
  },

  // --- Smart 400 (PME 1 only) - Partial ---
  {
    id: 'gndi-400-part-pme1',
    name: 'Smart 400',
    operator: 'GNDI NotreDame',
    type: 'Apartamento',
    coparticipationType: 'partial',
    logoColor: 'bg-orange-700',
    description: 'Acomodação individual.',
    hospitals: ['Hospital NotreCare', 'Modelo'],
    categories: [CAT_PME_1],
    coverage: 'Sorocaba, Itu, Votorantim, Araçoiaba da Serra, Iperó, Ibiúna, Boituva entre outras dezenas de cidades de São Paulo.',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_PARTIAL_GNDI,
    prices: {
      [AgeRange.RANGE_0_18]: 344.33,
      [AgeRange.RANGE_19_23]: 464.77,
      [AgeRange.RANGE_24_28]: 549.27,
      [AgeRange.RANGE_29_33]: 573.88,
      [AgeRange.RANGE_34_38]: 593.05,
      [AgeRange.RANGE_39_43]: 652.36,
      [AgeRange.RANGE_44_48]: 848.07,
      [AgeRange.RANGE_49_53]: 1102.50,
      [AgeRange.RANGE_54_58]: 1433.25,
      [AgeRange.RANGE_59_PLUS]: 2065.74,
    },
  },
  // --- Smart 400 (PME 1 only) - Full ---
  {
    id: 'gndi-400-full-pme1',
    name: 'Smart 400',
    operator: 'GNDI NotreDame',
    type: 'Apartamento',
    coparticipationType: 'full',
    logoColor: 'bg-orange-700',
    description: 'Acomodação individual.',
    hospitals: ['Hospital NotreCare', 'Modelo'],
    categories: [CAT_PME_1],
    coverage: 'Sorocaba, Itu, Votorantim, Araçoiaba da Serra, Iperó, Ibiúna, Boituva entre outras dezenas de cidades de São Paulo.',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_GNDI,
    prices: {
      [AgeRange.RANGE_0_18]: 241.04,
      [AgeRange.RANGE_19_23]: 325.35,
      [AgeRange.RANGE_24_28]: 384.50,
      [AgeRange.RANGE_29_33]: 401.72,
      [AgeRange.RANGE_34_38]: 415.14,
      [AgeRange.RANGE_39_43]: 456.66,
      [AgeRange.RANGE_44_48]: 593.66,
      [AgeRange.RANGE_49_53]: 771.76,
      [AgeRange.RANGE_54_58]: 1003.29,
      [AgeRange.RANGE_59_PLUS]: 1446.04,
    },
  },

  // --- Smart 400 (PME 2-29) - Partial ---
  {
    id: 'gndi-400-part-pme',
    name: 'Smart 400',
    operator: 'GNDI NotreDame',
    type: 'Apartamento',
    coparticipationType: 'partial',
    logoColor: 'bg-orange-700',
    description: 'Acomodação individual.',
    hospitals: ['Hospital NotreCare', 'Modelo'],
    categories: [CAT_PME_2, CAT_PME_30],
    coverage: 'Sorocaba, Itu, Votorantim, Araçoiaba da Serra, Iperó, Ibiúna, Boituva entre outras dezenas de cidades de São Paulo.',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_PARTIAL_GNDI,
    prices: {
      [AgeRange.RANGE_0_18]: 275.46,
      [AgeRange.RANGE_19_23]: 371.81,
      [AgeRange.RANGE_24_28]: 439.41,
      [AgeRange.RANGE_29_33]: 459.10,
      [AgeRange.RANGE_34_38]: 474.44,
      [AgeRange.RANGE_39_43]: 521.88,
      [AgeRange.RANGE_44_48]: 678.44,
      [AgeRange.RANGE_49_53]: 881.97,
      [AgeRange.RANGE_54_58]: 1146.56,
      [AgeRange.RANGE_59_PLUS]: 1652.54,
    },
  },
  // --- Smart 400 (PME 2-29) - Full ---
  {
    id: 'gndi-400-full-pme',
    name: 'Smart 400',
    operator: 'GNDI NotreDame',
    type: 'Apartamento',
    coparticipationType: 'full',
    logoColor: 'bg-orange-700',
    description: 'Acomodação individual.',
    hospitals: ['Hospital NotreCare', 'Modelo'],
    categories: [CAT_PME_2, CAT_PME_30],
    coverage: 'Sorocaba, Itu, Votorantim, Araçoiaba da Serra, Iperó, Ibiúna, Boituva entre outras dezenas de cidades de São Paulo.',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_GNDI,
    prices: {
      [AgeRange.RANGE_0_18]: 192.83,
      [AgeRange.RANGE_19_23]: 260.29,
      [AgeRange.RANGE_24_28]: 307.61,
      [AgeRange.RANGE_29_33]: 321.39,
      [AgeRange.RANGE_34_38]: 332.12,
      [AgeRange.RANGE_39_43]: 365.34,
      [AgeRange.RANGE_44_48]: 474.94,
      [AgeRange.RANGE_49_53]: 617.42,
      [AgeRange.RANGE_54_58]: 802.65,
      [AgeRange.RANGE_59_PLUS]: 1156.85,
    },
  },

  // ==========================================================================
  // FÊNIX MEDICAL
  // Color: Slate-600 (Dark Grey)
  // ==========================================================================

  // PME 1: Select Plus (Same Prices as PME 2-29)
  {
    id: 'fenix-none-pme1',
    name: 'Select Plus',
    operator: 'Fênix Medical',
    type: 'Enfermaria',
    coparticipationType: 'none',
    logoColor: 'bg-slate-600',
    description: 'Uso livre.',
    hospitals: ['Hospital Santo Antônio'],
    categories: [CAT_PME_1],
    coverage: 'Sorocaba e Votorantim',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_NONE,
    prices: {
      [AgeRange.RANGE_0_18]: 190.00,
      [AgeRange.RANGE_19_23]: 215.00,
      [AgeRange.RANGE_24_28]: 249.45,
      [AgeRange.RANGE_29_33]: 250.64,
      [AgeRange.RANGE_34_38]: 251.94,
      [AgeRange.RANGE_39_43]: 301.00,
      [AgeRange.RANGE_44_48]: 412.00,
      [AgeRange.RANGE_49_53]: 500.00,
      [AgeRange.RANGE_54_58]: 660.00,
      [AgeRange.RANGE_59_PLUS]: 890.00,
    },
  },
  {
    id: 'fenix-full-pme1',
    name: 'Select Plus',
    operator: 'Fênix Medical',
    type: 'Enfermaria',
    coparticipationType: 'full',
    logoColor: 'bg-slate-600',
    description: 'Plano econômico.',
    hospitals: ['Hospital Santo Antônio'],
    categories: [CAT_PME_1],
    coverage: 'Sorocaba e Votorantim',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_FENIX,
    prices: {
      [AgeRange.RANGE_0_18]: 148.20,
      [AgeRange.RANGE_19_23]: 167.70,
      [AgeRange.RANGE_24_28]: 194.57,
      [AgeRange.RANGE_29_33]: 195.50,
      [AgeRange.RANGE_34_38]: 196.51,
      [AgeRange.RANGE_39_43]: 234.78,
      [AgeRange.RANGE_44_48]: 321.58,
      [AgeRange.RANGE_49_53]: 390.00,
      [AgeRange.RANGE_54_58]: 514.80,
      [AgeRange.RANGE_59_PLUS]: 694.20,
    },
  },

  // PF: Select Plus (Specific Prices)
  {
    id: 'fenix-none-pf',
    name: 'Select Plus',
    operator: 'Fênix Medical',
    type: 'Enfermaria',
    coparticipationType: 'none',
    logoColor: 'bg-slate-600',
    description: 'Uso livre.',
    hospitals: ['Hospital Santo Antônio'],
    categories: [CAT_PF],
    coverage: 'Sorocaba e Votorantim',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_NONE,
    prices: {
      [AgeRange.RANGE_0_18]: 300.00,
      [AgeRange.RANGE_19_23]: 300.00,
      [AgeRange.RANGE_24_28]: 310.00,
      [AgeRange.RANGE_29_33]: 311.48,
      [AgeRange.RANGE_34_38]: 323.09,
      [AgeRange.RANGE_39_43]: 400.00,
      [AgeRange.RANGE_44_48]: 588.54,
      [AgeRange.RANGE_49_53]: 650.00,
      [AgeRange.RANGE_54_58]: 750.00,
      [AgeRange.RANGE_59_PLUS]: 1100.00,
    },
  },
  {
    id: 'fenix-full-pf',
    name: 'Select Plus',
    operator: 'Fênix Medical',
    type: 'Enfermaria',
    coparticipationType: 'full',
    logoColor: 'bg-slate-600',
    description: 'Plano econômico.',
    hospitals: ['Hospital Santo Antônio'],
    categories: [CAT_PF],
    coverage: 'Sorocaba e Votorantim',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_FENIX,
    prices: {
      [AgeRange.RANGE_0_18]: 234.00,
      [AgeRange.RANGE_19_23]: 234.00,
      [AgeRange.RANGE_24_28]: 241.80,
      [AgeRange.RANGE_29_33]: 242.95,
      [AgeRange.RANGE_34_38]: 252.01,
      [AgeRange.RANGE_39_43]: 312.00,
      [AgeRange.RANGE_44_48]: 459.06,
      [AgeRange.RANGE_49_53]: 507.00,
      [AgeRange.RANGE_54_58]: 585.00,
      [AgeRange.RANGE_59_PLUS]: 858.00,
    },
  },

  // PME 2-29: Select Plus (Specific Prices)
  {
    id: 'fenix-none-pme',
    name: 'Select Plus',
    operator: 'Fênix Medical',
    type: 'Enfermaria',
    coparticipationType: 'none',
    logoColor: 'bg-slate-600',
    description: 'Uso livre.',
    hospitals: ['Hospital Santo Antônio'],
    categories: [CAT_PME_2, CAT_PME_30],
    coverage: 'Sorocaba e Votorantim',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_NONE,
    prices: {
      [AgeRange.RANGE_0_18]: 190.00,
      [AgeRange.RANGE_19_23]: 215.00,
      [AgeRange.RANGE_24_28]: 249.45,
      [AgeRange.RANGE_29_33]: 250.64,
      [AgeRange.RANGE_34_38]: 251.94,
      [AgeRange.RANGE_39_43]: 301.00,
      [AgeRange.RANGE_44_48]: 412.00,
      [AgeRange.RANGE_49_53]: 500.00,
      [AgeRange.RANGE_54_58]: 660.00,
      [AgeRange.RANGE_59_PLUS]: 890.00,
    },
  },
  {
    id: 'fenix-full-pme',
    name: 'Select Plus',
    operator: 'Fênix Medical',
    type: 'Enfermaria',
    coparticipationType: 'full',
    logoColor: 'bg-slate-600',
    description: 'Plano econômico.',
    hospitals: ['Hospital Santo Antônio'],
    categories: [CAT_PME_2, CAT_PME_30],
    coverage: 'Sorocaba e Votorantim',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_FENIX,
    prices: {
      [AgeRange.RANGE_0_18]: 148.20,
      [AgeRange.RANGE_19_23]: 167.70,
      [AgeRange.RANGE_24_28]: 194.57,
      [AgeRange.RANGE_29_33]: 195.50,
      [AgeRange.RANGE_34_38]: 196.51,
      [AgeRange.RANGE_39_43]: 234.78,
      [AgeRange.RANGE_44_48]: 321.58,
      [AgeRange.RANGE_49_53]: 390.00,
      [AgeRange.RANGE_54_58]: 514.80,
      [AgeRange.RANGE_59_PLUS]: 694.20,
    },
  },

  // ==========================================================================
  // UNIMED SOROCABA
  // Color: Green-600
  // ==========================================================================

  // PME 1 (Specific Prices)
  {
    id: 'unimed-flex-pme1',
    name: 'Unipart Max',
    operator: 'Unimed Sorocaba',
    type: 'Enfermaria',
    coparticipationType: 'full',
    logoColor: 'bg-green-600',
    description: 'Melhor rede médica da região.',
    hospitals: ['Hospital Unimed', 'Santa Lucinda'],
    categories: [CAT_PME_1],
    coverage: 'Sorocaba e região, com atendimento de urgência e emergência a nível nacional',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_UNIMED,
    prices: {
      [AgeRange.RANGE_0_18]: 244.91,
      [AgeRange.RANGE_19_23]: 293.89,
      [AgeRange.RANGE_24_28]: 352.67,
      [AgeRange.RANGE_29_33]: 423.20,
      [AgeRange.RANGE_34_38]: 507.84,
      [AgeRange.RANGE_39_43]: 609.41,
      [AgeRange.RANGE_44_48]: 731.29,
      [AgeRange.RANGE_49_53]: 914.11,
      [AgeRange.RANGE_54_58]: 1042.09,
      [AgeRange.RANGE_59_PLUS]: 1417.25,
    },
  },

  // PME 2+ (Specific Prices)
  {
    id: 'unimed-flex-pme',
    name: 'Unipart Max',
    operator: 'Unimed Sorocaba',
    type: 'Enfermaria',
    coparticipationType: 'full',
    logoColor: 'bg-green-600',
    description: 'Melhor rede médica da região.',
    hospitals: ['Hospital Unimed', 'Santa Lucinda'],
    categories: [CAT_PME_2, CAT_PME_30],
    coverage: 'Sorocaba e região, com atendimento de urgência e emergência a nível nacional',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_UNIMED,
    prices: {
      [AgeRange.RANGE_0_18]: 224.50,
      [AgeRange.RANGE_19_23]: 269.40,
      [AgeRange.RANGE_24_28]: 323.28,
      [AgeRange.RANGE_29_33]: 387.94,
      [AgeRange.RANGE_34_38]: 465.52,
      [AgeRange.RANGE_39_43]: 558.62,
      [AgeRange.RANGE_44_48]: 670.35,
      [AgeRange.RANGE_49_53]: 837.94,
      [AgeRange.RANGE_54_58]: 955.25,
      [AgeRange.RANGE_59_PLUS]: 1299.14,
    },
  },

  // ==========================================================================
  // EVA SAÚDE
  // PME 2+
  // Variant: Only Full Copart
  // Color: Teal (#009CA6)
  // ==========================================================================
  {
    id: 'eva-enf',
    name: 'Eva Prata',
    operator: 'Eva Saúde',
    type: 'Enfermaria',
    coparticipationType: 'full',
    logoColor: 'bg-[#009CA6]',
    description: 'Foco na saúde da mulher.',
    hospitals: ['Hospital Evangélico'],
    categories: [CAT_PME_2, CAT_PME_30],
    coverage: 'Sorocaba',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_EVA,
    prices: {
      [AgeRange.RANGE_0_18]: 144.00,
      [AgeRange.RANGE_19_23]: 169.00,
      [AgeRange.RANGE_24_28]: 190.00,
      [AgeRange.RANGE_29_33]: 205.00,
      [AgeRange.RANGE_34_38]: 221.00,
      [AgeRange.RANGE_39_43]: 255.00,
      [AgeRange.RANGE_44_48]: 344.00,
      [AgeRange.RANGE_49_53]: 443.00,
      [AgeRange.RANGE_54_58]: 565.00,
      [AgeRange.RANGE_59_PLUS]: 803.00,
    },
  },

  // ==========================================================================
  // AMIL
  // PME 2+
  // Variants: Full & Partial
  // Color: Blue-600
  // ==========================================================================
  {
    id: 'amil-part',
    name: 'Amil Prata SP',
    operator: 'Amil',
    type: 'Apartamento',
    coparticipationType: 'partial',
    logoColor: 'bg-blue-600',
    description: 'Cobertura nacional.',
    hospitals: ['Hospital Evangélico', 'Hospital NotreCare'],
    categories: [CAT_PME_2, CAT_PME_30],
    coverage: 'Abrangência a nível nacional, São Paulo, Rio de Janeiro, Pernambuco, Amazonas entre outros estados',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_PARTIAL_AMIL,
    prices: {
      [AgeRange.RANGE_0_18]: 353.26,
      [AgeRange.RANGE_19_23]: 413.31,
      [AgeRange.RANGE_24_28]: 504.24,
      [AgeRange.RANGE_29_33]: 605.09,
      [AgeRange.RANGE_34_38]: 635.34,
      [AgeRange.RANGE_39_43]: 698.87,
      [AgeRange.RANGE_44_48]: 873.59,
      [AgeRange.RANGE_49_53]: 960.95,
      [AgeRange.RANGE_54_58]: 1201.19,
      [AgeRange.RANGE_59_PLUS]: 2102.08,
    },
  },
  {
    id: 'amil-full',
    name: 'Amil Prata SP',
    operator: 'Amil',
    type: 'Apartamento',
    coparticipationType: 'full',
    logoColor: 'bg-blue-600',
    description: 'Cobertura nacional.',
    hospitals: ['Hospital Evangélico', 'Hospital NotreCare'],
    categories: [CAT_PME_2, CAT_PME_30],
    coverage: 'Abrangência a nível nacional, São Paulo, Rio de Janeiro, Pernambuco, Amazonas entre outros estados',
    gracePeriods: GRACE_PERIOD_STANDARD,
    copayFees: COPAY_FULL_AMIL,
    prices: {
      [AgeRange.RANGE_0_18]: 264.95,
      [AgeRange.RANGE_19_23]: 309.99,
      [AgeRange.RANGE_24_28]: 378.19,
      [AgeRange.RANGE_29_33]: 453.83,
      [AgeRange.RANGE_34_38]: 476.52,
      [AgeRange.RANGE_39_43]: 524.17,
      [AgeRange.RANGE_44_48]: 655.21,
      [AgeRange.RANGE_49_53]: 720.73,
      [AgeRange.RANGE_54_58]: 900.91,
      [AgeRange.RANGE_59_PLUS]: 1576.56,
    },
  },
];
